# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1296829949);
user_pref("app.update.lastUpdateTime.background-update-timer", 1296829521);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1296829876);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1296829790);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1296829639);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1295574804);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.10");
user_pref("browser.tabs.autoHide", true);
user_pref("extensions.adblockplus.currentVersion", "1.3.3");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.10");
user_pref("extensions.lastAppVersion", "3.6.10");
user_pref("extensions.newAddons", false);
user_pref("extensions.skype_toolbar.version", "5.0.0.6906");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 1);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.privacy.disable_button.view_cookies", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1298202940);
//user_pref("network.proxy.http_port", );
//user_pref("network.proxy.http", "");
